name: StreamingPlugin Build and Make

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build . -t screenstreamer-builder

      - name: Run make
        run: |
          mkdir -p build_output
          docker run --rm -v ${{ github.workspace }}:/project screenstreamer-builder make
          
          # Check if the expected output exists (spoiler it doesn't)
          if [ -d "output" ]; then
            cp -r output/* build_output/
          elif [ -f "screenstreaming.wps" ]; then
            cp screenstreaming.wps build_output/
          else
            echo "No output found, build may have failed."
            exit 1
          fi

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: StreamingAromaPlugin
          path: build_output/
          retention-days: 7  # Adjust retention period
